spring:
  main:
    allow-circular-dependencies: true
    allow-circular-references: true
  application:
    name: ecommerce
  datasource:
    url: jdbc:mysql://localhost:3309/ecommercedb
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      #ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5Dialect
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

endpoints:
  shutdown:
    enabled: true

security:
  jwt:
    secret-Key: 45D81EC1EF61DF9AD8D3E5BB397F9
    token-duration: 1D

